# Conda-forge doesn't like this, but we are cloning the repo from git.
# Apparently it wastes CI resources.
# Honestly, I don't have a good other way to do this.
# We include a few patches in our distribution, including versioneer
# This will give us a version number that increments
{% set data = load_setup_py_data() %}

package:
  name: scikit-image
  version: {{ data.get('version') }}

source:
  git_url: https://github.com/hmaarrfk/scikit-image
  patches:
    - versioneer.diff
    - pr_3159_simplify_build_process.diff
    - pr_3057_feature_bayer2rgb.diff
    - pr_3069_feature_rectangle_perimeter.diff
    - pr_3077_feature_transform_geometry.diff
    - pr_3103_bugfix_ellipsis_fitting_32bit.diff
    #- pr_3126_imageio_preferred_over_PIL.diff

build:
  # number: {{ datetime.datetime.now().strftime("%Y%m%d") }}
  number: 1
  skip: True  # [py<35]
  script:
    - rm -rf skimage/viewer/tests  # we don't depend on Qt
    - python -m pip install --no-deps --ignore-installed .
  entry_points:
    - skivi = skimage.scripts.skivi:main

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - m2-patch  # [win]
  host:
    - python
    - pip
    - numpy 1.11.3
    - cython >=0.23
    - scipy >=0.17
    - numpydoc >=0.6
    - msinttypes  # [win]
    - m2-patch  # [win]
  run:
    - python >=3.5
    - {{ pin_compatible('numpy') }}
    - scipy >=0.17
    - networkx >=1.8
    - pillow >=4.3.0
    - dask-core >=0.15
    - toolz >=0.7.4
    - pywavelets >=0.4.0
    - dask-core >=0.9.0
    - cloudpickle >=0.2.1
    - imageio >=2.1.0
    - matplotlib >=2.0.0

test:
  requires:
    - pytest
    - pytest-cov
  imports:
    - skimage
  commands:
    - pytest --pyargs skimage

about:
  home: http://scikit-image.org/
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Image processing routines for SciPy.'

extra:
  recipe-maintainers:
    - ivoflipse
    - jakirkham
    - jni
    - Korijn
    - msarahan
    - ocefpaf
    - soupault
