travis:
  secure:
    BINSTAR_TOKEN: UZGW+IgyRxyklEUva/wfSlr86ud9uNkq9bUXLZVlsHva9nNfqqvxCAv1mQ9NgUNt6Ll7wTq541+iYEioNBlFencZEg3PlRhNSbwy+M9fdoCyv0d9OfTKV+IdX45cfpzvxKOpf+n9mlEl5QyDCPySezPsDUp0L4jC+Q48dcl8AD6W06DfdbGHITJUnGEH1i1KomiLaCZryAlP4Hznd8xXX3rvcaFdDPpsKWQxQxr3ugevH7y44bCR69/iYSAsNbha4u1beFWNEZSH28QHv3Lq15lJ262Hl8PTvfoJFcvaa7PZnXHqI94cfVEywxuPo4TCojc+2TGxURfMfm44o3+6zJb5dthLxrJzX/2p7NiyCNiHU5FQ+LocDtLiKYP97PclNE7N+UaR3qi1OFIlPge16bz8bb7gZdtkXPkEnNikFmxCbw8zrNcO5Et7/PQhaErJg5WoiI7LvDwG490dU4y4FO+1zLzhOEBG4L5YIlsYJu720vTiL7zN3Fc0B/enkwuCceUoFNu9bANC/dXFx+PYMNHfqVj8yDCke8zwxk1r1klhXd8fe4dZb7ujrxgJQfbORSnxm5ZXQvNjxB6VQ4KQCLmQxEP2+Vn+jzdu9l2amzJgyfl4axv2W1TvHKv7KI/X1drFN7hV4ADAZKhEx6sxyTHpnwWrer/iXgm399iqFFw=
appveyor:
  secure:
    BINSTAR_TOKEN: u69YOH2yvrsPgxnt9MHl1CcO0FvxgWknUHhjprl52PbgvsJSPW6RjTTaSqPJXfNH
